// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-zRqIQnjXlHvdoxcTbpR1qx0L5rvqd9E',
    appId: '1:869179861968:web:143db9e67ed5ffed34a7d5',
    messagingSenderId: '869179861968',
    projectId: 'classes-12554',
    authDomain: 'classes-12554.firebaseapp.com',
    storageBucket: 'classes-12554.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMkV6kQW9I_PSZ8g11a3qb0_s6ZwSYqvQ',
    appId: '1:869179861968:android:249178c605cf54d234a7d5',
    messagingSenderId: '869179861968',
    projectId: 'classes-12554',
    storageBucket: 'classes-12554.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM3gu0V_8M5pYjFWAwCSLOBld4EwaxUp0',
    appId: '1:869179861968:ios:31e1c36dd0599bd334a7d5',
    messagingSenderId: '869179861968',
    projectId: 'classes-12554',
    storageBucket: 'classes-12554.firebasestorage.app',
    iosBundleId: 'com.example.classes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM3gu0V_8M5pYjFWAwCSLOBld4EwaxUp0',
    appId: '1:869179861968:ios:31e1c36dd0599bd334a7d5',
    messagingSenderId: '869179861968',
    projectId: 'classes-12554',
    storageBucket: 'classes-12554.firebasestorage.app',
    iosBundleId: 'com.example.classes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-zRqIQnjXlHvdoxcTbpR1qx0L5rvqd9E',
    appId: '1:869179861968:web:2df580d30959a70e34a7d5',
    messagingSenderId: '869179861968',
    projectId: 'classes-12554',
    authDomain: 'classes-12554.firebaseapp.com',
    storageBucket: 'classes-12554.firebasestorage.app',
  );

}